#!/bin/sh

if [ "$dev18" = "" ]; then
    pd="/usr/lib/blackbox"
else
    pd="$dev18"
fi

sd=`readlink -f .`

# fix Ubuntu-specific problems:
unset UBUNTU_MENUPROXY
unset GTK_MODULES
export LIBOVERLAY_SCROLLBAR=0

# export LD_DEBUG=all
if test -f "${sd}"/blackbox; then
    edir="${sd}"
else 
    edir="${pd}"
fi
tput init
bold=`tput setaf 2`
plain=`tput sgr0`
echo Running blackbox executable from ${bold}"${edir}"${plain} against BlackBox primary ${bold}"${pd}"${plain}


env \
	BB_PRIMARY_DIR="${pd}" BB_SECONDARY_DIR="${sd}" \
	"${edir}"/blackbox
#	"${pd}"/blackbox

