#!/bin/sh

if [ "$dev18" = "" ]; then
    pd="/usr/lib/blackbox"
else
    pd="$dev18"
fi

sd=`readlink -f .`

# fix Ubuntu-specific problems:
unset UBUNTU_MENUPROXY
unset GTK_MODULES
export LIBOVERLAY_SCROLLBAR=0

# export LD_DEBUG=all
if test -f "${sd}"/blackbox; then
    executable="${sd}"/blackbox
    echo Running blackbox executable from "${sd}"
else 
    executable="${pd}"/blackbox
    echo Running blackbox executable from "${pd}"
fi

env \
	BB_PRIMARY_DIR="${pd}" BB_SECONDARY_DIR="${sd}" \
	$executable
#	"${pd}"/blackbox

